# Generated by Django 4.2.7 on 2023-12-30 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='john doe (default)', max_length=200, null=True)),
                ('title', models.CharField(default='This is the default, title change it in profile', max_length=200, null=True)),
                ('desc', models.CharField(default='Hey, there this is a default text description about you that you can change on after clicking on "Edit"', max_length=200, null=True)),
                ('profile_img', models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
